- players: benny
  games: 11
  numbers: 32
  positions: short
- players: frank
  games: 13
  numbers: 18
  positions: third
- players: hugh
  games: 12
  numbers: 28
  positions: first
- players: neil
  games: 8
  numbers: 29
  positions: left
- players: russell
  games: 9
  numbers: 21
  positions: second
- players: theodore
  games: 10
  numbers: 3
  positions: center
